services:
  telegram-dumper:
    build:
      context: telegram-dumper/
    environment:
      TELEGRAM_API_ID:
      TELEGRAM_API_HASH:
    volumes:
      - type: bind
        source: ./telegram-dumper/src/
        target: /var/app/src/
      - type: bind
        source: ./telegram-dumper/sessions/
        target: /var/app/sessions/
      - type: bind
        source: ./data/
        target: /var/app/data/
  stt:
    build:
      context: stt/
    volumes:
      - type: bind
        source: ./stt/src/
        target: /var/app/src/
      - type: bind
        source: ./huggingface/
        target: /root/.cache/huggingface/
      - type: bind
        source: ./data/
        target: /var/app/data/
